# The URL the site will be built for
title = "Anaël Lasserre"
base_url = "https://voluxyy.github.io"

theme = "duckquill"

[markdown]
# Whether to do syntax highlighting
# Theme can be customised by setting the `highlight_theme` variable to a theme supported by Zola
highlight_code = true

[extra]
issues_url = "https://github.com/voluxyy/voluxyy.github.io/issues"

[extra.nav]
links = [
    {url = "/whoami", name = "WhoAmI"},
    {url = "/tasks", name = "Tasks"},
]

[extra.footer]
links = [
    {url = "/whoami", name = "WhoAmI"},
    {url = "/tasks", name = "Tasks"},
]